version: '3'

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
    - 4444:4444
    restart: always


  bot:
    build:
      context: .
#    restart: always
    volumes:
      - ./app:/app
    command: sh -c "python3 bot.py"
    depends_on:
      - selenium

#  app:
#    build:
#      context: .
#    restart: always
#    volumes:
#    - ./app/:/app/
#    command: sh -c "python3 streaming.py"
#    depends_on:
#      - selenium

